name: base-user-image
# This is the standard conda configuration file. Use this file to list
# the conda packages that you need installed in your environment.
channels:
  - conda-forge

dependencies:
  # Items required for basic level functionality
  - gh-scoped-creds==4.1
  - git==2.51.0
  - ipython==9.9.0
  - jupyter-resource-usage=1.2.0
  - jupyterhub==5.5.1
  - jupyterlab==4.6.3
  - jupyter-archive==3.4.0
  - jupyter_server==2.17.0
  - jupyterlab-git==0.51.2
  - jupyterlab_rise==0.43.1
  - jupytext==1.16.6
  - nbgitpuller==1.2.2
  - notebook==7.6.2
  - python==3.11.*
  - pip==25.1.1
  - regex==2025.11.3
  - sqlite==3.51.1

  # r2d installs jupyter-rsession-proxy, but in the base python env, not in the updated one
  - jupyter-rsession-proxy==2.3.0

  # vscode
  - code-server==4.106.2
  - jupyter-vscode-proxy==0.7
  - jupyter-server-proxy==4.4.0

  # data science
  - datascience==0.18.1
  - matplotlib==3.10.3
  - numpy==2.3.5
  - geopandas==1.1.0
  - openpyxl==3.1.5
  - pandas==2.3.0
  - plotly==6.1.2
  - scikit-learn==1.7.0
  - scipy==1.15.2
  - seaborn==0.13.2
  - statsmodels==0.14.4
  - sympy==1.14.0

  # umd
  - adlfs
  - argopy
  - awscli
  - black
  - boto3
  - bottleneck
  - cartopy
  - cdsapi
  - cfgrib
  - cf_xarray
  - ciso
  - cmocean
  - contextily
  - dask-geopandas
  - dask-ml
  - datashader
  - descartes
  - duckdb-cli
  - earthaccess
  - eofs
  - erddapy
  - esmpy
  - fastjmd95
  - flox
  - fsspec
  - gcm_filters
  - gcsfs>=2025
  - gdal
  - gh
  - geocube
  - geopy
  - geoviews-core
  - git-lfs
  - google-cloud-sdk
  - gsw
  - h5netcdf
  - h5py
  - holoviews
  - hvplot
  - icechunk
  - intake
  # wait for zarr v3 compat - https://github.com/intake/intake-esm/issues/727
  - intake-esm<2025.2.3
  - intake-geopandas
  - intake-stac
  - intake-xarray
  - ipdb
  - ipykernel
  - ipyleaflet
  - ipympl
  - ipytree
  - ipywidgets
  - jupyterlab_code_formatter
  - jupyterlab-lsp
  - jupyterlab-myst
  - jupyter-panel-proxy
  - jupyter-sshd-proxy
  - kerchunk
  - libgdal-arrow-parquet
  - libgdal-netcdf
  - line_profiler
  - lonboard
  - lxml
  - lz4
  - matplotlib-base
  - memory_profiler
  - metpy
  - nb_conda_kernels
  - nbstripout
  - nc-time-axis
  - netcdf4
  - numbagg
  - numcodecs
  - numpy_groupies
  - obstore
  - odc-stac>=0.4.0
  - openssh
  - panel
  # wait for zarr v3 compat - https://github.com/OceanParcels/Parcels/issues/1819
  #- parcels
  - param
  - planetary-computer
  - pop-tools
  - pot
  - pyarrow
  - pycamhd
  - pydap
  - pystac
  - pystac-client
  - python-blosc
  - python-duckdb
  - python-gist
  - python-graphviz
  - python-lsp-ruff
  - python-xxhash
  - rasterio
  - rclone
  - rechunker
  - rio-cogeo
  - rioxarray
  - ruff
  - s3fs
  - satpy
  - scikit-image
  - sparse
  - snakeviz
  - stackstac
  - tiledb-py
  - timezonefinder
  - virtualizarr
  - watermark
  - xarray
  - xarrayutils
  - xarray_leaflet
  - xarray-spatial
  - xbatcher
  # https://github.com/conda-forge/xcape-feedstock/pull/22
  #- xcape
  - xclim
  - xesmf
  - xgboost
  - xgcm
  - xhistogram
  - xmip
  - xmitgcm
  - xpublish
  - xrft
  - xskillscore
  - xxhash
  - xvec
  - zarr>=3.0.8

  # pip installed packages, conda is preferred
  - pip:
    - jupyterlab-a11y-checker==0.2.5

    # useful for debugging python package issues
    - pip-tree==4.0.0
    - pipdeptree==2.28.0

    # r2d installs jupyter-shiny-proxy, but in the base python env, not in the updated one
    - jupyter-shiny-proxy==1.3
    - jupysql==0.10.15
    - nbconvert[webpdf]==7.16.6
    - otter-grader==6.1.3
